######################################################################
# Automatically generated by qmake (2.01a) Tue May 20 20:02:07 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . model
INCLUDEPATH += . model

# Input
HEADERS += Test.h model/Picture.h model/PictureList.h
FORMS += untitled.ui
SOURCES += main.cpp Test.cpp model/Picture.cpp model/PictureList.cpp
